# This is a basic workflow that is automatically trigged on every commit

name: Automated workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 push


jobs:

  test:

    runs-on: ubuntu-latest
    
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install cypress
      run: npm install
    - name: Run test on Chrome
      run: npm run cy-chrome
    - name: Run test on Firefox
      run: npm run cy-firefox
    - name: Run test on Electron
      run: npm run cy-electron
    - name: Run test on Edge
      run: npm run cy-edge
